version: '3'
services:

  gateway:
    image: hyperioxx/frontman:latest
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      - FRONTMAN_REDIS_URL=redis://redis:6379
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379