name: Build and Push Docker Image on Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sobolevn/misspell-fixer-action@master
        with:
          options: '-rsvn .'
